### ISSUE TITLE
Upstream / distro status?

### ISSUE THREAD

**Issue by mbroz** [vlastavesely/kuznyechik-kernel#2]
Hi,
I added support for new Veracrypt modes (that include Kuznyechik in cipher chains) to cryptsetup tcrypt mode https://github.com/mbroz/cryptsetup/commit/24aba9a514f6d9bb3fa1697fa464d936329a1d30.

It was tested with your implementation and it seems to work nicely. Any plans to send this to upstream kernel? Or at least package it in more distros? I can mention link to this repo in cryptsetup release notes if needed.

Anyway, thanks! Without your module it would be impossible to support new Veracrypt modes.

**Comment by vlastavesely** [comment]
Hi, I have an another implementation of Kuznyechik somewhere. It should enable SSE optimization. What  I am planning right now, is to create a debian package. For kernel upstream it is not well tested, I think :)

**Comment by mbroz** [comment]
Could you push the new version to github please?

**Comment by vlastavesely** [comment]
It is is another repository and not implemented as kernel module. I have to finish it first. Give me a few days and I will finish it and push it here.

**Comment by vlastavesely** [comment]
The implementation can be found at https://github.com/kuzcrypt/kuznyechik

Right now, it needs testing. Once it is stable, I will update the kernel module implementation.

**Comment by vlastavesely** [comment]
In Debian Buster, there is a package `gost-crypto-dkms` that works just nice. So I guess that this issue loses its meaning and therefore I am closing it.
