### ISSUE TITLE
Kernel Module doesn't seem to be working with modern Kernel.

### ISSUE THREAD

**Issue by AmNe5iA** [vlastavesely/kuznyechik-kernel#4]
Despite having the dkms module installed on my system I am unable to use the kuznyechik-xts-plain64 cipher.
See command logs below:

$ uname -a
Linux HTCU01 6.1.0-9-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.27-1 (2023-05-08) x86_64 GNU/Linux

$ sudo dkms status
Deprecated feature: REMAKE_INITRD (/var/lib/dkms/kuznyechik-kernel/1.0/source/dkms.conf)
Deprecated feature: REMAKE_INITRD (/var/lib/dkms/kuznyechik-kernel/1.0/source/dkms.conf)
kuznyechik-kernel/1.0, 6.1.0-8-amd64, x86_64: installed
kuznyechik-kernel/1.0, 6.1.0-9-amd64, x86_64: installed

$ cat /proc/crypto
name         : ccm(aes)
driver       : ccm_base(ctr(aes-aesni),cbcmac(aes-aesni))
module       : ccm
priority     : 300
refcnt       : 4
selftest     : passed
internal     : no
type         : aead
async        : no
blocksize    : 1
ivsize       : 16
maxauthsize  : 16
geniv        : <none>

name         : ctr(aes)
driver       : ctr(aes-aesni)
module       : ctr
priority     : 300
refcnt       : 4
selftest     : passed
internal     : no
type         : skcipher
async        : no
blocksize    : 1
min keysize  : 16
max keysize  : 32
ivsize       : 16
chunksize    : 16
walksize     : 16

name         : cbcmac(aes)
driver       : cbcmac(aes-aesni)
module       : ccm
priority     : 300
refcnt       : 7
selftest     : passed
internal     : no
type         : shash
blocksize    : 1
digestsize   : 16

name         : blake2b-512
driver       : blake2b-512-generic
module       : blake2b_generic
priority     : 100
refcnt       : 1
selftest     : passed
internal     : no
type         : shash
blocksize    : 128
digestsize   : 64

name         : blake2b-384
driver       : blake2b-384-generic
module       : blake2b_generic
priority     : 100
refcnt       : 1
selftest     : passed
internal     : no
type         : shash
blocksize    : 128
digestsize   : 48

name         : blake2b-256
driver       : blake2b-256-generic
module       : blake2b_generic
priority     : 100
refcnt       : 1
selftest     : passed
internal     : no
type         : shash
blocksize    : 128
digestsize   : 32

name         : blake2b-160
driver       : blake2b-160-generic
module       : blake2b_generic
priority     : 100
refcnt       : 1
selftest     : passed
internal     : no
type         : shash
blocksize    : 128
digestsize   : 20

name         : crc32c
driver       : crc32c-generic
module       : crc32c_generic
priority     : 100
refcnt       : 1
selftest     : passed
internal     : no
type         : shash
blocksize    : 1
digestsize   : 4

name         : crc64-rocksoft
driver       : crc64-rocksoft-generic
module       : crc64_rocksoft_generic
priority     : 200
refcnt       : 2
selftest     : passed
internal     : no
type         : shash
blocksize    : 1
digestsize   : 8

name         : crct10dif
driver       : crct10dif-generic
module       : crct10dif_generic
priority     : 100
refcnt       : 1
selftest     : passed
internal     : no
type         : shash
blocksize    : 1
digestsize   : 2

name         : crct10dif
driver       : crct10dif-pclmul
module       : crct10dif_pclmul
priority     : 200
refcnt       : 2
selftest     : passed
internal     : no
type         : shash
blocksize    : 1
digestsize   : 2

name         : crc32
driver       : crc32-pclmul
module       : crc32_pclmul
priority     : 200
refcnt       : 1
selftest     : passed
internal     : no
type         : shash
blocksize    : 1
digestsize   : 4

name         : crc32c
driver       : crc32c-intel
module       : crc32c_intel
priority     : 200
refcnt       : 5
selftest     : passed
internal     : no
type         : shash
blocksize    : 1
digestsize   : 4

name         : __ghash
driver       : cryptd(__ghash-pclmulqdqni)
module       : cryptd
priority     : 50
refcnt       : 1
selftest     : passed
internal     : yes
type         : ahash
async        : yes
blocksize    : 16
digestsize   : 16

name         : ghash
driver       : ghash-clmulni
module       : ghash_clmulni_intel
priority     : 400
refcnt       : 1
selftest     : passed
internal     : no
type         : ahash
async        : yes
blocksize    : 16
digestsize   : 16

name         : __ghash
driver       : __ghash-pclmulqdqni
module       : ghash_clmulni_intel
priority     : 0
refcnt       : 1
selftest     : passed
internal     : yes
type         : shash
blocksize    : 16
digestsize   : 16

name         : sha384
driver       : sha384-avx2
module       : sha512_ssse3
priority     : 170
refcnt       : 1
selftest     : passed
internal     : no
type         : shash
blocksize    : 128
digestsize   : 48

name         : sha512
driver       : sha512-avx2
module       : sha512_ssse3
priority     : 170
refcnt       : 1
selftest     : passed
internal     : no
type         : shash
blocksize    : 128
digestsize   : 64

name         : sha384
driver       : sha384-avx
module       : sha512_ssse3
priority     : 160
refcnt       : 1
selftest     : passed
internal     : no
type         : shash
blocksize    : 128
digestsize   : 48

name         : sha512
driver       : sha512-avx
module       : sha512_ssse3
priority     : 160
refcnt       : 1
selftest     : passed
internal     : no
type         : shash
blocksize    : 128
digestsize   : 64

name         : sha384
driver       : sha384-ssse3
module       : sha512_ssse3
priority     : 150
refcnt       : 1
selftest     : passed
internal     : no
type         : shash
blocksize    : 128
digestsize   : 48

name         : sha512
driver       : sha512-ssse3
module       : sha512_ssse3
priority     : 150
refcnt       : 1
selftest     : passed
internal     : no
type         : shash
blocksize    : 128
digestsize   : 64

name         : sha384
driver       : sha384-generic
module       : sha512_generic
priority     : 100
refcnt       : 1
selftest     : passed
internal     : no
type         : shash
blocksize    : 128
digestsize   : 48

name         : sha512
driver       : sha512-generic
module       : sha512_generic
priority     : 100
refcnt       : 1
selftest     : passed
internal     : no
type         : shash
blocksize    : 128
digestsize   : 64

name         : __xctr(aes)
driver       : cryptd(__xctr-aes-aesni)
module       : cryptd
priority     : 450
refcnt       : 1
selftest     : passed
internal     : yes
type         : skcipher
async        : yes
blocksize    : 1
min keysize  : 16
max keysize  : 32
ivsize       : 16
chunksize    : 16
walksize     : 16

name         : xctr(aes)
driver       : xctr-aes-aesni
module       : aesni_intel
priority     : 400
refcnt       : 1
selftest     : passed
internal     : no
type         : skcipher
async        : yes
blocksize    : 1
min keysize  : 16
max keysize  : 32
ivsize       : 16
chunksize    : 16
walksize     : 16

name         : __xctr(aes)
driver       : __xctr-aes-aesni
module       : aesni_intel
priority     : 400
refcnt       : 1
selftest     : passed
internal     : yes
type         : skcipher
async        : no
blocksize    : 1
min keysize  : 16
max keysize  : 32
ivsize       : 16
chunksize    : 16
walksize     : 16

name         : __gcm(aes)
driver       : cryptd(__generic-gcm-aesni)
module       : cryptd
priority     : 450
refcnt       : 1
selftest     : passed
internal     : yes
type         : aead
async        : yes
blocksize    : 1
ivsize       : 12
maxauthsize  : 16
geniv        : <none>

name         : gcm(aes)
driver       : generic-gcm-aesni
module       : aesni_intel
priority     : 400
refcnt       : 1
selftest     : passed
internal     : no
type         : aead
async        : yes
blocksize    : 1
ivsize       : 12
maxauthsize  : 16
geniv        : <none>

name         : __rfc4106(gcm(aes))
driver       : cryptd(__rfc4106-gcm-aesni)
module       : cryptd
priority     : 450
refcnt       : 1
selftest     : passed
internal     : yes
type         : aead
async        : yes
blocksize    : 1
ivsize       : 8
maxauthsize  : 16
geniv        : <none>

name         : rfc4106(gcm(aes))
driver       : rfc4106-gcm-aesni
module       : aesni_intel
priority     : 400
refcnt       : 1
selftest     : passed
internal     : no
type         : aead
async        : yes
blocksize    : 1
ivsize       : 8
maxauthsize  : 16
geniv        : <none>

name         : __gcm(aes)
driver       : __generic-gcm-aesni
module       : aesni_intel
priority     : 400
refcnt       : 1
selftest     : passed
internal     : yes
type         : aead
async        : no
blocksize    : 1
ivsize       : 12
maxauthsize  : 16
geniv        : <none>

name         : __rfc4106(gcm(aes))
driver       : __rfc4106-gcm-aesni
module       : aesni_intel
priority     : 400
refcnt       : 1
selftest     : passed
internal     : yes
type         : aead
async        : no
blocksize    : 1
ivsize       : 8
maxauthsize  : 16
geniv        : <none>

name         : __xts(aes)
driver       : cryptd(__xts-aes-aesni)
module       : cryptd
priority     : 451
refcnt       : 3
selftest     : passed
internal     : yes
type         : skcipher
async        : yes
blocksize    : 16
min keysize  : 32
max keysize  : 64
ivsize       : 16
chunksize    : 16
walksize     : 16

name         : xts(aes)
driver       : xts-aes-aesni
module       : aesni_intel
priority     : 401
refcnt       : 3
selftest     : passed
internal     : no
type         : skcipher
async        : yes
blocksize    : 16
min keysize  : 32
max keysize  : 64
ivsize       : 16
chunksize    : 16
walksize     : 16

name         : __ctr(aes)
driver       : cryptd(__ctr-aes-aesni)
module       : cryptd
priority     : 450
refcnt       : 1
selftest     : passed
internal     : yes
type         : skcipher
async        : yes
blocksize    : 1
min keysize  : 16
max keysize  : 32
ivsize       : 16
chunksize    : 16
walksize     : 16

name         : ctr(aes)
driver       : ctr-aes-aesni
module       : aesni_intel
priority     : 400
refcnt       : 1
selftest     : passed
internal     : no
type         : skcipher
async        : yes
blocksize    : 1
min keysize  : 16
max keysize  : 32
ivsize       : 16
chunksize    : 16
walksize     : 16

name         : __cts(cbc(aes))
driver       : cryptd(__cts-cbc-aes-aesni)
module       : cryptd
priority     : 450
refcnt       : 1
selftest     : passed
internal     : yes
type         : skcipher
async        : yes
blocksize    : 16
min keysize  : 16
max keysize  : 32
ivsize       : 16
chunksize    : 16
walksize     : 16

name         : cts(cbc(aes))
driver       : cts-cbc-aes-aesni
module       : aesni_intel
priority     : 400
refcnt       : 1
selftest     : passed
internal     : no
type         : skcipher
async        : yes
blocksize    : 16
min keysize  : 16
max keysize  : 32
ivsize       : 16
chunksize    : 16
walksize     : 16

name         : __cbc(aes)
driver       : cryptd(__cbc-aes-aesni)
module       : cryptd
priority     : 450
refcnt       : 1
selftest     : passed
internal     : yes
type         : skcipher
async        : yes
blocksize    : 16
min keysize  : 16
max keysize  : 32
ivsize       : 16
chunksize    : 16
walksize     : 16

name         : cbc(aes)
driver       : cbc-aes-aesni
module       : aesni_intel
priority     : 400
refcnt       : 1
selftest     : passed
internal     : no
type         : skcipher
async        : yes
blocksize    : 16
min keysize  : 16
max keysize  : 32
ivsize       : 16
chunksize    : 16
walksize     : 16

name         : __ecb(aes)
driver       : cryptd(__ecb-aes-aesni)
module       : cryptd
priority     : 450
refcnt       : 1
selftest     : passed
internal     : yes
type         : skcipher
async        : yes
blocksize    : 16
min keysize  : 16
max keysize  : 32
ivsize       : 0
chunksize    : 16
walksize     : 16

name         : ecb(aes)
driver       : ecb-aes-aesni
module       : aesni_intel
priority     : 400
refcnt       : 1
selftest     : passed
internal     : no
type         : skcipher
async        : yes
blocksize    : 16
min keysize  : 16
max keysize  : 32
ivsize       : 0
chunksize    : 16
walksize     : 16

name         : __xts(aes)
driver       : __xts-aes-aesni
module       : aesni_intel
priority     : 401
refcnt       : 3
selftest     : passed
internal     : yes
type         : skcipher
async        : no
blocksize    : 16
min keysize  : 32
max keysize  : 64
ivsize       : 16
chunksize    : 16
walksize     : 32

name         : __ctr(aes)
driver       : __ctr-aes-aesni
module       : aesni_intel
priority     : 400
refcnt       : 1
selftest     : passed
internal     : yes
type         : skcipher
async        : no
blocksize    : 1
min keysize  : 16
max keysize  : 32
ivsize       : 16
chunksize    : 16
walksize     : 16

name         : __cts(cbc(aes))
driver       : __cts-cbc-aes-aesni
module       : aesni_intel
priority     : 400
refcnt       : 1
selftest     : passed
internal     : yes
type         : skcipher
async        : no
blocksize    : 16
min keysize  : 16
max keysize  : 32
ivsize       : 16
chunksize    : 16
walksize     : 32

name         : __cbc(aes)
driver       : __cbc-aes-aesni
module       : aesni_intel
priority     : 400
refcnt       : 1
selftest     : passed
internal     : yes
type         : skcipher
async        : no
blocksize    : 16
min keysize  : 16
max keysize  : 32
ivsize       : 16
chunksize    : 16
walksize     : 16

name         : __ecb(aes)
driver       : __ecb-aes-aesni
module       : aesni_intel
priority     : 400
refcnt       : 1
selftest     : passed
internal     : yes
type         : skcipher
async        : no
blocksize    : 16
min keysize  : 16
max keysize  : 32
ivsize       : 0
chunksize    : 16
walksize     : 16

name         : aes
driver       : aes-aesni
module       : aesni_intel
priority     : 300
refcnt       : 7
selftest     : passed
internal     : no
type         : cipher
blocksize    : 16
min keysize  : 16
max keysize  : 32

name         : pkcs1pad(rsa,sha256)
driver       : pkcs1pad(rsa-generic,sha256)
module       : kernel
priority     : 100
refcnt       : 1
selftest     : passed
internal     : no
type         : akcipher

name         : hmac(sha1)
driver       : hmac(sha1-generic)
module       : kernel
priority     : 100
refcnt       : 5
selftest     : passed
internal     : no
type         : shash
blocksize    : 64
digestsize   : 20

name         : hmac(sha256)
driver       : hmac(sha256-generic)
module       : kernel
priority     : 100
refcnt       : 5
selftest     : passed
internal     : no
type         : shash
blocksize    : 64
digestsize   : 32

name         : lzo-rle
driver       : lzo-rle-scomp
module       : kernel
priority     : 0
refcnt       : 1
selftest     : passed
internal     : no
type         : scomp

name         : lzo-rle
driver       : lzo-rle-generic
module       : kernel
priority     : 0
refcnt       : 1
selftest     : passed
internal     : no
type         : compression

name         : lzo
driver       : lzo-scomp
module       : kernel
priority     : 0
refcnt       : 9
selftest     : passed
internal     : no
type         : scomp

name         : lzo
driver       : lzo-generic
module       : kernel
priority     : 0
refcnt       : 1
selftest     : passed
internal     : no
type         : compression

name         : zlib-deflate
driver       : zlib-deflate-scomp
module       : kernel
priority     : 0
refcnt       : 1
selftest     : passed
internal     : no
type         : scomp

name         : deflate
driver       : deflate-scomp
module       : kernel
priority     : 0
refcnt       : 1
selftest     : passed
internal     : no
type         : scomp

name         : deflate
driver       : deflate-generic
module       : kernel
priority     : 0
refcnt       : 2
selftest     : passed
internal     : no
type         : compression

name         : aes
driver       : aes-generic
module       : kernel
priority     : 100
refcnt       : 1
selftest     : passed
internal     : no
type         : cipher
blocksize    : 16
min keysize  : 16
max keysize  : 32

name         : sha224
driver       : sha224-generic
module       : kernel
priority     : 100
refcnt       : 1
selftest     : passed
internal     : no
type         : shash
blocksize    : 64
digestsize   : 28

name         : sha256
driver       : sha256-generic
module       : kernel
priority     : 100
refcnt       : 7
selftest     : passed
internal     : no
type         : shash
blocksize    : 64
digestsize   : 32

name         : sha1
driver       : sha1-generic
module       : kernel
priority     : 100
refcnt       : 8
selftest     : passed
internal     : no
type         : shash
blocksize    : 64
digestsize   : 20

name         : md5
driver       : md5-generic
module       : kernel
priority     : 0
refcnt       : 1
selftest     : passed
internal     : no
type         : shash
blocksize    : 64
digestsize   : 16

name         : ecb(cipher_null)
driver       : ecb-cipher_null
module       : kernel
priority     : 100
refcnt       : 1
selftest     : passed
internal     : no
type         : skcipher
async        : no
blocksize    : 1
min keysize  : 0
max keysize  : 0
ivsize       : 0
chunksize    : 1
walksize     : 1

name         : digest_null
driver       : digest_null-generic
module       : kernel
priority     : 0
refcnt       : 1
selftest     : passed
internal     : no
type         : shash
blocksize    : 1
digestsize   : 0

name         : compress_null
driver       : compress_null-generic
module       : kernel
priority     : 0
refcnt       : 1
selftest     : passed
internal     : no
type         : compression

name         : cipher_null
driver       : cipher_null-generic
module       : kernel
priority     : 0
refcnt       : 1
selftest     : passed
internal     : no
type         : cipher
blocksize    : 1
min keysize  : 0
max keysize  : 0

name         : rsa
driver       : rsa-generic
module       : kernel
priority     : 100
refcnt       : 1
selftest     : passed
internal     : no
type         : akcipher

name         : dh
driver       : dh-generic
module       : kernel
priority     : 100
refcnt       : 1
selftest     : passed
internal     : no
type         : kpp

$ sudo cryptsetup luksFormat Test --cipher=kuznyechik-xts-plain64       --key-size=512 --hash=whirlpool --verify-passphrase

WARNING!
========
This will overwrite data on Test irrevocably.

Are you sure? (Type 'yes' in capital letters): YES
Enter passphrase for Test: 
Verify passphrase: 
device-mapper: reload ioctl on temporary-cryptsetup-1109435 (254:4) failed: No such file or directory
Failed to setup dm-crypt key mapping for device Test.
Check that kernel supports kuznyechik-xts-plain64 cipher (check syslog for more info).

**Comment by vlastavesely** [comment]
Do you use secure boot?

**Comment by AmNe5iA** [comment]
No

**Comment by vlastavesely** [comment]
And what happens if you try to `modprobe` the modules manually?

**Comment by AmNe5iA** [comment]
$ sudo modprobe kuznyechik.ko
modprobe: FATAL: Module kuznyechik.ko not found in directory /lib/modules/6.1.0-9-amd64

**Comment by AmNe5iA** [comment]
$ sudo modprobe kuznyechik
modprobe: ERROR: could not insert 'kuznyechik': Invalid argument

**Comment by AmNe5iA** [comment]
$ sudo modinfo kuznyechik
filename:       /lib/modules/6.1.0-9-amd64/updates/dkms/kuznyechik.ko
alias:          crypto-kuznyechik
alias:          kuznyechik
description:    128bit cipher as specified in GOST R 34-12.2015
license:        GPL
depends:        
retpoline:      Y
name:           kuznyechik
vermagic:       6.1.0-8-amd64 SMP preempt mod_unload modversions 
sig_id:         PKCS#7
signer:         DKMS module signing key

**Comment by vlastavesely** [comment]
The system is Debian Bookworm, right?

I am planning to install Bookworm very soon and then I will check if I encounter the same issue.

**Comment by AmNe5iA** [comment]
Yes bookworm

**Comment by vlastavesely** [comment]
I have installed Debian Bookworm and I can confirm the issue. But I am not able to `modprobe` even a module from a package from the official repo.

As Debian Bookworm is not released yet, I shall wait until it is released and then, if the issue prevails. If it does, I shall fix it (or at least investigate more).

**Comment by AmNe5iA** [comment]
Fair enough. Thanks

**Comment by vlastavesely** [comment]
It should be fixed now. Please test it.

**Comment by AmNe5iA** [comment]
Hmm. Its still not working:

$ sudo cryptsetup luksFormat Test --cipher=kuznyechik-xts-plain64 --key-size=512 --hash=whirlpool --verify-passphrase

WARNING!
========
This will overwrite data on Test irrevocably.

Are you sure? (Type 'yes' in capital letters): YES
Enter passphrase for Test: 
Verify passphrase: 
device-mapper: reload ioctl on temporary-cryptsetup-47093 (254:4) failed: No such file or directory
Failed to setup dm-crypt key mapping for device Test.
Check that kernel supports kuznyechik-xts-plain64 cipher (check syslog for more info).

$ sudo modprobe kuznyechik 
modprobe: ERROR: could not insert 'kuznyechik': Invalid argument
$ sudo modinfo kuznyechik 
filename:       /lib/modules/6.1.0-9-amd64/updates/dkms/kuznyechik.ko
alias:          crypto-kuznyechik
alias:          kuznyechik
description:    128bit cipher as specified in GOST R 34-12.2015
license:        GPL
depends:        
retpoline:      Y
name:           kuznyechik
vermagic:       6.1.0-8-amd64 SMP preempt mod_unload modversions 
sig_id:         PKCS#7
signer:         DKMS module signing key
sig_key:        [redacted]
sig_hashalgo:   sha256
signature:      [redacted]

**Comment by vlastavesely** [comment]
I do not think you are using the latest version. The field ‘License’ in modinfo should print ‘GPL v2’ and not just ‘GPL’.

Try to uninstall the package completely, then install it again and ensure that in ‘kuznyechik.c’ there is `MODULE_LICENSE("GPL v2")` at the end and the structure `kuznyechik_alg` has the field `.cra_priority` set.

**Comment by AmNe5iA** [comment]
Sorry I hadn't realised you had updated the code. I'll uninstall and install the new code and try again.

**Comment by AmNe5iA** [comment]
$ sudo cryptsetup luksFormat Test --cipher=kuznyechik-xts-plain64 --key-size=512 --hash=whirlpool --verify-passphrase

WARNING!
========
This will overwrite data on Test irrevocably.

Are you sure? (Type 'yes' in capital letters): YES
Enter passphrase for Test: 
Verify passphrase: 
$ sudo modprobe kuznyechik
$ sudo modinfo kuznyechik
filename:       /lib/modules/6.1.0-9-amd64/updates/dkms/kuznyechik.ko
alias:          crypto-kuznyechik
alias:          kuznyechik
description:    128bit cipher as specified in GOST R 34-12.2015
license:        GPL v2
depends:        
retpoline:      Y
name:           kuznyechik
vermagic:       6.1.0-9-amd64 SMP preempt mod_unload modversions 
sig_id:         PKCS#7
signer:         DKMS module signing key
sig_key:        [redacted]
sig_hashalgo:   sha256
signature:  [redacted]

Appears to be working corectly now.  Thanks

**Comment by AmNe5iA** [comment]
Appears to be working corectly now. Thanks
